src/components/TeeForm.vue, src/questionnaire/trackResults.ts
Resolves #12 
Adds a link in the form's checkbox hint before the form's "send" button. 
Link to : http://mission-transition.beta.gouv.fr/donnee-personnelles-et-cookies
---
=> custom hint for checkbox

packages/web/src/questionnaire/trackResults.ts
Les infos du formulaire dans le champ de texte libre `FORM_NEEDS` ne semble plus remonter dans Brevo
=> hotfix: missing attribute field in brevo form data

.github/workflows/test-data.yml
Rename wrong "build" to "validate-data" with explicit name.
=> refactor: rename ci job

packages/web/src/components/TeeSidebar.vue, packages/web/src/components/TeeTrack.vue, packages/web/src/stores/tracks.ts
Dans la version précédente de `preprod` quand on utilisait la _sidebar_ (fil d'Ariane) le comportement n'était pas satisfaisant : si on revenait en arrière avec la _sidebar_ il fallait alors re-cliquer deux fois sur un choix déjà sélectionné pour passer à la piste suivante... 
Le comportement souhaité lors du retour en arrière au clic sur un des boutons de la _sidebar_ est le suivant : 
1. Je clique sur le bouton de la piste à laquelle je souhaite revenir dans la _sidebar_ ;
2. La piste de question voulue réapparaît avec : 
- Le choix que j'avais précédemment choisi est déjà sélectionné ;
- Le bouton 'Suivant'  est donc déjà actif ;
3. Je peux directement cliquer sur 'Suivant' :
- Mon choix est enregistré ;
- La nouvelle piste de question apparaît ;
Ce comportement attendu n'était pas …
=> fix: debug back to track keeping user's selection within track component

packages/data/README.md, packages/data/src/buildJsonOutput.ts
A [last minute file rename](https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/133/commits/b8afdb305d95a653dccb848badb0be2e83214e7d) broke the build procedure. 
This PR fixes the file name references (along with doc rewording).
=> fix: file rename broke the build procedure

.github/workflows/tests.yml
Currently, unit tests are only run locally (with `npm run test -w packages/backend`).
This PR adds the unit tests in continuous integration to avoid shipping with failing tests.
=> CI: run unit tests

packages/backend/src/domain/eligibility.ts, packages/backend/tests/eligibilite.test.ts
To avoid unnoticed filtering problems, publicodes would require to have all variables defined when evaluating a rule, or otherwise throw an error. 
However, if filtering problems are not noticed in preproduction, then the final user gets the error, which is not the best ID. In particular, we missed that in the "Je ne sais pas par où commencer" route was not defining the `questionnaire . objectif prioritaire` property, used to filter some programs. 
This hotfix allows to have undefined publicodes rules. The introduced behavior is to keep the programs with undefined `afficher à l'utilisateur si` rule.
=> hotfix: filtering problem in "Je ne sais pas par où commencer" 

packages/data/package.json
The `build-json-output-watch` was launching two nodemon concurrently, and `npm run dev-front` would throw a third. As `generateProgramType.ts` and `buildJsonOutput.ts` were generating files, nodemon would restart two or three times each service before arriving at a stable state. 
I replaced the call to `concurrently` with a sequential call to `generateProgramType.ts`  followed by `buildJsonOutput.ts`.
Benefits : 
- More readable, shorter script
- No more script triggering the other
- We had to run them sequentially at least for the first generation, so now this is guaranteed. 
Drawbacks : 
- Program type is regenerated at each change, even though most changes are completely unrelated. But it does not take long, so... who cares ?
=> fix: stop the nodemon generation madness

packages/web/public/css/custom.css, packages/web/src/assets/custom.css, packages/web/src/components/TeeResults.vue, packages/web/src/types/programTypes.ts
Complementary resolution of #165 (itself part of #168)
Result =>
=> PR - feat: add aid info in miniature cards

package.json
Just fix the `npm run dev-back` command by adding the missing `run` keyword on the following command:  
`npx concurrently "npm build-json-output-watch" "npm run dev -w packages/backend"`
replace by
`npx concurrently "npm run build-json-output-watch" "npm run dev -w packages/backend"`
=> fix: add 'run' on npm `dev-back` command

packages/web/src/router/index.ts, packages/web/src/router/redirection.ts, packages/web/src/types/routeType.ts
Ajout des redirections sur la homepage des anciennes url de l'applicatif symfony
#208 
- Un fichier dédié `redirection.ts` pour la gestion des redirections dans le router a été ajouter dans le dossier `src/router/`.  
Il contient l'ensemble des routes à rediriger.
- Un enum des noms route a été ajouté (`src/types/routeType.ts`) car il me semble plus pertinent de fonctionner avec des noms de routes (`name`) plutôt qu'avec le `path`. Ceci permet de pouvoir changer les url sans changer de partout dans le code. Et avec les enums ont peux avoir une liste accessible des noms de routes
=> feat(redirection): ajout des redirections

packages/backend/src/domain/eligibility.ts
For no other reason than it was easier to write, the `publicodes` chunks were evaluated twice for filtering. 
As performance is a concern, this PR proposes a quick win, by evaluating the code only once. 
The modified `filterPrograms` function is unit tested. 
Hint : easier to review in [split mode](https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/221/files?diff=split&w=0) 
Ref ticket : #164
=> perf: quick win for filtering programs with publicodes

packages/web/src/components/home/TeeCta.vue, packages/web/src/pages/TeeHomePage.vue
=> fix: reduce margins and padding around CTA in home page

packages/web/public/css/custom.css, packages/web/src/WidgetApp.ce.vue, packages/web/src/assets/custom.css, packages/web/src/components/TeeTrack.vue, packages/web/src/pages/TeeQuestionnairePage.vue
solves #200 (finishes the job)
- Coller le bloc jaune (_alias_ le "callout") au _header_ (_alias_ la "navbar")
- Ajouter un  peu de marge en haut de la _sidebar_ de gauche (_alias_ le "fil d'Ariane"), pour éviter que celle-ci soit trop collée à la navbar
- Cacher le fil d'Ariane sur la première question
- Quelques modifs de css pour tenter de compacter un peu le texte contenu dans le callout.
---
=> fix: adjust UI and UX on first track + css addons

packages/web/src/types/publicodesObjects.ts
Tout était en place pour le filtrage par secteur dans le parcours sans Siret.
S'appuye sur la branche `refactor/typing-track`. À rebaser après avoir mergé la PR #210.
J'ai juste mis à jour le mapping entre secteur d'activité (issu du questionnaire dans le parcours sans siret) et les codes NAF niveau 1 associés, en accord avec ce que j'avais partagé [sur le notion](https://www.notion.so/accelerateur-transition-ecologique-ademe/Exploration-de-donn-es-de-secteur-d-activit-5d685fc564bd455597757688ce632645).
Principale différence, le secteur `Autre secteur d'activité` râtisse plutôt large, les autres plutôt moins large.
Closes #181 et closes #173
=> feat: Mise-à-jour des filtrages des secteurs d'activité (parcours sans siret)

packages/web/src/utils/helpers.ts
- #310 
Le pb vient d'une regex utilisant les lookbehind pour le formatage d'un texte avec un valeur de type monétaire  ou pourcentage.
https://javascript.info/regexp-lookahead-lookbehind#lookbehind
https://caniuse.com/js-regexp-lookbehind
La regex utilisant les lookbehind est replacé par une regex plus simple et tout aussi fonctionnelle mais accepter les navigateur tel que safari et IE
=> fix: replace lookahead regex to simpler regex to work on safari and IE

packages/backend/src/contact/domain/types.ts, packages/web/src/questionnaire/trackResults.ts
- cf #460 
Le siret (re)devient obligatoire sur la formulaire (front) et sur le typage (back)
Attention, il n'y pas pas encore de validation sur les différents champs du formulaire
=> feat: on contact form, siret field is now required

packages/web/vite.config.ts
hotfix pour les envoies des event Matomo. Depuis que les headers CSP ont été mis en prod les envoie des stats matomo ne sont plus fait car le nom et le script matomo n'est pas accepté par la configuration des CSP
=> fix: headers CSP for matomo

packages/backend/src/establishment/controller/establishmentController.ts, packages/web/src/questionnaire/trackStructureSiret.ts, packages/web/src/types/formTypes.ts, packages/web/src/utils/requests.ts
Annule et remplace la PR #96 
> ### Context
> 
> The Sirene API is currently served as a "POST /api/insee/get_by_siret" endpoint which requires the data to be provided in the request body.
> ### Suggestion
> 
> I would suggest two changes :
> 
>  - First, the API should be exposed as a GET endpoint (as the name suggests). The siret could then be provided as a path parameter instead, e.g. "/api/insee/get_by_siret/83014132100034"
>   - I suggest to change the API endpoint name, because of following shortcomings with the current name :
>         "insee" should not be part of the name, as the data provider is actually none of the business of the frontend. It may change in the future (e.g. switching to API entreprise), and a change of routes should not be required in this case.
> …
=> refactor(establishment): `get /establishments/{siret}`

packages/backend/src/app.ts, packages/backend/src/program/application/programService.ts, packages/backend/src/program/controller/programsController.ts, packages/backend/src/program/infrastructure/publicodes.ts, packages/backend/src/program/infrastructure/publicodesService.ts, packages/backend/tests/program/filterPrograms.test.ts, packages/backend/tests/program/preprocessPrograms.test.ts
Fix #164
PR #371 introduit le filtrage côté backend. 
Cette PR profite de ce changement pour résoudre #164 en initialisant les règles publicodes de tous les dispositifs au lancement du serveur, plutôt qu'à chaque appel d'API. 
Gain de performance observé en local : on passe de + de 2.5s à moins de 1s. Les tests effectués sur le serveur de preprod donnent les mêmes résultats. 
Des tests ont été cassé par les changements introduits : 
- l'initialisation de publicodes suppose des identifiants de programme uniques (on fait un mapping "identifiant" > "moteur publicodes"), ce qui n'était pas le cas dans certains tests jusqu'à présent. 
- On testé que le filtrage échouait en cas d'instruction publicodes invalide. L'erreur est maintenant remontée dès l'instanciation du service (donc en pratique …
=> refactor: Publicodes s'initialise au lancement du serveur d'API

packages/web/src/service/api/programApi.ts
Le filtre sur les valeurs envoyé au point d'entré d'api "api/programs" ne peuvent pas être égale à null car la method js `.toString` est utilisé et donc renvoie une fatale erreur
=> hotfix: clean values to null sent to the backend "api/programs" entry point

packages/data/programs/audits-clef-verte.yaml, packages/data/programs/baisse-les-watts.yaml, packages/data/programs/bonus-ecologique.yaml, packages/data/programs/coup-de-pouce-chauffage.yaml, packages/data/programs/enviroveille.yaml, packages/data/programs/etude-performance-produits.yaml, packages/data/programs/extreme-defi-mobilite.yaml, packages/data/programs/formation-engager-entreprise-transition-ecologique.yaml, packages/data/programs/formations-du-cfde.yaml, packages/data/programs/formations-tee.yaml, packages/data/programs/investissement-vte-vert.yaml, packages/data/programs/prime-a-la-conversion.yaml, packages/data/programs/renovation-energetique.yaml, packages/data/programs/repar-acteurs.yaml, packages/data/programs/trophees-crisalide-eco-activites.yaml, packages/data/schemas/program-data-schema.json, packages/data/schemas/program-with-publicodes-schema.json, packages/data/tools/XL2yaml/XL2yaml.py, packages/web/src/components/program/detail/ProgramDetail.vue, packages/web/src/components/program/detail/ProgramForm.vue, packages/web/src/components/program/detail/ProgramObjective.vue, packages/web/src/pages/TeeCatalogPage.vue, packages/web/src/translations/fr/program.ts, packages/web/src/types/program/programTypes.ts
- Ajoute un CTA "contactez un conseiller" qui renvoie vers le formulaire de contact (scroll en bas de page) pour tous les dispositifs sauf ceux "activables en autonomie.
- ajoute un champ "activable en autonomie" dans les programmes
- ajoute un bouton en fonctionation de la présence ou non du champ dans le programme affiché
- Change le titre du formulaire de contact en "contactez un conseiller
- enleve le bandeau en bas de page "nous contacter" de toutes les fiches dispositifs de l'annuaire
RAS sur l'implem, modifications qui touchent peu à la logique.
Un dispositif non autonome : https://tee-preprod-pr715.osc-fr1.scalingo.io/aides-entreprise/amo-chaufferie-biomasse
Un dispositif autonome : https://tee-preprod-pr715.osc-fr1.scalingo.io/aides-entreprise/extreme-defi-mobilite
=> feat: create "activable en autonomie" program field, add a CTA button on program display

packages/backend/src/establishment/domain/establishmentFeatures.ts, packages/common/src/establishment/validator.ts, packages/web/src/components/track/form/TrackSiret.vue, packages/web/src/service/api/establishmentApi.ts, packages/web/src/translations/fr.ts
Fix le validator SIRET qui laissait passer les SIREN ce qui causait l'erreur dans le backend.
Fix la gestion des erreurs du back dans le front (J'ai repris du code déjà présent dans l'api program du front et pensais naivement que c'était géré par le try catch)
Utilise l'api recherche-entreprise comme fallback en cas d'erreur de l'api sirene pour ajouter une couche de robustesse.
close #741
=> fix: establishment search now works with a SIREN search

packages/web/vite.config.ts
- ajout d'une directive CSP pour l'environnement de développement, permettant l'utilisation de l'extension vue dev tool sur firefox
=> chore: update vite server config to enable firefox vue dev tool usage

package-lock.json, package.json, packages/web/.eslintrc-auto-import.json, packages/web/index.html, packages/web/package.json, packages/web/src/WebApp.vue, packages/web/src/auto-imports.d.ts, packages/web/src/components/program/detail/ProgramDetail.vue, packages/web/src/main.ts, packages/web/vite.config.ts
- Ajout du plugin unheadVue
- Déclaration des titles et meta description par défaut dans app.vue
- Déclaration des titles et meta personnalisés lors de l'affichage d'un programme. 
Test fonctionnel réalisé : 
- vérif des champs concernés sur la page d'accueil
- vérif des champs concernés lors de l'ouverture d'un programme via le catalogue
- vérifs des champs lors d'un retour sur la page d'accueil après ouverture d'un programme  (non trivial !)
close #666
=> improve: Use specific head title and meta description when a program is displayed

packages/common/src/program/types.ts, packages/web/src/utils/program/programFilters.ts
- fix fonction de filtre par opérateur = on vérifie maintenant avec une comparaison partielle entre les opérateurs sélectionnés et l'opérateur de contact de chaque programme (pour valider le cas "CCI ou CMA") 
- ajout des opérateurs de contacts manquants
=> Fix fonction de filtre par opérateur dans l'annuaire

packages/web/src/components/program/list/ProgramList.vue, packages/web/src/router/routes.ts
- inversion de la priorité pour récupérer l'objective entre celui des filtres et des tracks
- `reset` des `programs filters` quand on commence un nouveau parcours
note: La PR fixe aussi l'issue https://github.com/betagouv/mission-transition-ecologique/issues/816
=> fix: programs filters

libs/backend-ddd/src/program/infrastructure/publicodesService.ts, package-lock.json, package.json
La dépendance `publicodes` a été mis à jours ! (1.3.3)
=> Build: update publicodes

libs/backend-ddd/src/opportunity/domain/opportunityFeatures.ts
Avec l'ancienne implem, on mettait à jour le statut même si la transmission retournait une erreur.
=> fix: update brevo status only if transmit is sucessfull 

apps/web/src/utils/theme.ts
Changement du titre Economies d'énergie par Energie et changement du tag batiment par rénovation
=> Fix: Renommage des thématiques Energie et rénovation

apps/backend/project.json, apps/web/project.json, libs/backend-ddd/project.json, libs/common/project.json, libs/data/project.json, package.json
Petit refacto de la command `npm run ci` afin de passer par les command nx au lieu de l'enchaînement de `npm run`.
Ca permet d'éviter de lancer plusieurs fois la même commande en dependence comme `generate:program`
=> refactor: improve CI command to use nx

apps/web/src/service/api/opportunityApi.ts, libs/backend-ddd/src/opportunity/infrastructure/api/brevo/brevoContact.ts, libs/backend-ddd/src/opportunity/infrastructure/api/brevo/types.ts, libs/backend-ddd/src/opportunityHub/infrastructure/api/bpi/opportunityPayloadDTO.ts, libs/common/src/opportunity/opportunityTypes.ts, libs/data/tools/brevoExport/brevoExport.py
- Mise à jour dans le front de la variable utilisée
- Mise à jour du format de données transmis
- Mise à jour de la conversion domain -> brevo
- Création d'un cas EI sur brevo
- Mise à jour testée et validée sur Brevo
- Mise à jour de la donnée transmise à BPI. ???? 
J'ai pas mal d'incertitudes sur la partie BPI. 
1/ je ne suis pas certain de ce qu'on doit leur transmettre. Un nombre ? Une string ? ... 
2/ je ne comprend pas bien ce qui a été fait sur le fichier OpportunityPayloadDTO.ts. Pourquoi des getters privés ont-ils été créés ? Qu'est ce qu'ils apportent ? 
3/ je transmet directement this._companySize qui est un enum dont la valeur finale est un string  | un undefined dans un type string | number | undefined . Cela vous semble t'il correct ?
=> Fix: transmit establishment size in Opportunity

apps/web/src/assets/scss/card.scss, apps/web/src/components/objective/ThemeCard.vue
La règle scss est maintenant appliquée uniquement si on rajoute la classe fr-card__img--contain
=> Fix : Plus de marges blanches sur les cartes projets et programs

apps/web/src/components/element/TeeGroupBar.vue
Ajout de regles css pour avoir un ellipsis dès que la largeur n'est pas suffisante plutôt que de passer sur deux lignes
=> Fix : texte sur deux ligne pour la barre des critères d'éligibilité 

apps/web/src/components/element/TeeDsfrBreadcrumb.vue, apps/web/src/components/program/detail/ProgramHeader.vue, apps/web/src/components/program/eligibilityCriteria/TeeEligibilityCriteriaBar.vue, apps/web/src/components/project/details/ProjectHeader.vue, apps/web/src/router/index.ts
Ajout d'un timeOut à la création du router pour attendre la fin d'éventuelles transitions sur les pages et le chargement des éléments.
Ainsi on s'assure que l'élément ciblé par le tag passé dans l'url est bien présent sur la page au moment d'activer l'action de scroll.
=> feat: add delayed scrolling behavior to hash links

apps/web/src/components/TeeFooter.vue, apps/web/src/components/catalog/CatalogPrograms.vue, apps/web/src/components/catalog/CatalogProjects.vue, apps/web/src/components/element/TeeDsfrBreadcrumb.vue, apps/web/src/components/objective/ThemeSelect.vue, apps/web/src/pages/TeeAccessibilityPage.vue, apps/web/src/pages/TeeCatalogPage.vue, apps/web/src/pages/TeeLegalPage.vue, apps/web/src/pages/TeePersonalDataPage.vue, apps/web/src/pages/TeeStatPage.vue, apps/web/src/router/routes.ts, apps/web/src/stores/navigation.ts, apps/web/src/types/routeType.ts
- ajout du breadcrumb dans les catalogues projets + programs + page legale + page statistique + page données perso + page accessibilité 
- fix du lien questionnaire >> rollback sur le onBeforeMount du composant ThemeSelect (ajoutées pour le CTA pour si on a déjà une valeur d'objectif enregistrée, on passe directement à l'étape résultats ce qui causait le probleme au niveau du breadcrumb)
- adaptation du composant pour afficher les bons intitulés selon la route
- ajout margin bottom 
- remplacement de la méthode toSPliced par du slice dans teedsfrbreadcrumb pour résoudre le probleme de compatibilité (erreur sentry)
=> Fix : Correction fil d'ariane

apps/backend/.env.example, libs/backend-ddd/src/opportunity/domain/opportunityFeatures.ts, libs/backend-ddd/src/opportunity/infrastructure/api/brevo/brevoDeal.ts, libs/backend-ddd/src/opportunity/infrastructure/api/brevo/types.ts, libs/backend-ddd/src/opportunityHub/infrastructure/api/placedesentreprises/placeDesEntreprises.ts, libs/backend-ddd/src/project/application/projectService.ts, libs/backend-ddd/src/project/domain/projectFeatures.ts, libs/data/tools/brevoExport/brevoExport.py
La PR est fonctionnelle mais je ne suis pas super fan de son archi. 
L'idée est de modifier le statut sur brevo au lieu de la colonne envoyée (puis à terme de cacher la colonne envoyée sur le site Brevo).
"Problème" : le statut correspond à une ID dépendant de l'ID de la pipeline brevo.
Je considère que cet id n'est pas une donnée sensible et je l'ai donc hard codé. 
La solution proposée permet de ne pas dévoiler l'id de la pipeline de prod.
La solution proposé cassera si on modifie les pipeline utilisées sur brevo.
La seule solution pour que ce ne soit pas le cas serait de query brevo pour obtenir dynamiquement l'id mais ça augmente le nombre d'appel à des services externe et donc le temps des transaction ce qui ne me plait pas. 
Point annexes de la PR: 
- fix du script de récup des …
=> Feat: update opportunity status on transmission

apps/backend/.env.example, libs/backend-ddd/src/opportunity/infrastructure/api/brevo/brevoDeal.ts, libs/backend-ddd/src/opportunity/infrastructure/api/brevo/types.ts
Suite à un revirement de la personne en charge du suivi des opportunité BREVO, rollback du changement sur la mise à jour du statut.
=> rollback: brevo status update

apps/web/src/utils/theme.ts
- modifie l'ordre par défaut des themes -> permet d'adapter l'ordre des theme tag dans les pages catalogues
- modifie l'ordre des tags récupérés via les choix de l'utilisateur
objectif général : harmoniser l'ordre des themes avec celui défini dans l'étape "sélection d'un theme" du parcours "j'ai un projet en tête"
url de test:  https://tee-preprod-pr1068.osc-fr1.scalingo.io/
close #1052
=> refactor: reorder themes and adjust tag assignment logic

apps/web/src/components/project/list/ProjectList.vue, apps/web/src/components/questionnaire/result/list/ResultProjectList.vue, apps/web/src/translations/fr/project.ts
- ajoute une conditions pour afficher le counter des projets uniquement si un theme spécifique est séléctionné dans les tags
- modifie le condition d'affichage du composant ResultListNoResults pour éviter de surcharger le dom avec des div vides inutiles et qui poluent le spacing avec d'éventuelle classes css
- met à jour le texte de résumé pour la page de résultat des projets en supprimant la mention de la région
lien de test: https://tee-preprod-pr1069.osc-fr1.scalingo.io/
close #967
=> refactor: modify project lists to show or hide elements conditionally

libs/backend-ddd/src/opportunityHub/infrastructure/api/bpi/bpiFrance.ts
Ajout du playload de pour l'api bpi dans le monitoring d'exception
Permet d'avoir le detail du payload dans sentry car il manque ici par exemple
https://sentry.incubateur.net/organizations/betagouv/issues/119550/?environment=prod&project=-1&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=3
=> fix: add payload on monitoring exception from bpi api

apps/backend/src/controller/program/programsController.ts, apps/web/src/service/api/requestApi.ts, libs/backend-ddd/src/program/application/types.ts, libs/backend-ddd/src/program/domain/programFeatures.ts, libs/backend-ddd/src/program/domain/types.ts, libs/backend-ddd/src/program/index.ts
Features: 
- sépare les erreurs 404 des erreurs 500 dans le point d'API qui query un unique program
- ajoute un bout de code de gestion d'erreur d'api dans le front end. 
Questions : 
- Archi back OK (création du fichier type dans application) ?
- vérifier que le bout de code du front n'a pas de side effect.  => Veut-on vraiment avec toutes les erreurs catch dans le backend retourner un result.error dans le front. 
lié à #1257 
(Supprime le bug mais ne close pas au vu du message de Coline)
=> fix: program not found redirection 

apps/web/src/service/api/opportunityApi.ts, apps/web/src/utils/opportunity.ts
Fix afin de passer l'id du projet dans le cas d'un formulaire d'opportunité `project` au lieu du `projetTitle`
=> fix: sent project form with project id

apps/web/src/components/identification/TeeRegisterModal.vue, apps/web/src/components/identification/TeeRegisterSiret.vue, apps/web/src/components/identification/TeeRegisterSiretBar.vue, apps/web/src/utils/navigation.ts
- J'ai aussi un comportement etrange sur le champs SIRET lorsque je cherche mon entreprise et clique rapidement sur Enter. Le menu déroulant disparait et réapparait (ex ici avec le mot "camping". Sinon en attendant un peu il apparait une seule fois (ex avec le mot "hotel"). => on ne reset plus les résultats quand on relance une recherche comme ça on a pas l'effet bizarre de clignotement par contre comme le debounce est plus long qu'un retour de requete (qui du coup peut se faire instantanement avec entrée) on a bien deux requetes qui partent
Ces deux retour la sont fix avec un retour instantané en haut de page si la modale est ouverte
- lorsque je ne suis pas identifié, sur une fiche dispositif ou fiche projet, au clic sur le CTA en bas de page "je complète mon profil", le comportement du …
=> Fixes : scroll + search siret

apps/web/src/translations/fr/program.ts
Corrected the capitalization and punctuation of "SIRET" in the French translation file. This ensures consistency and adherence to proper naming conventions.
=> fix: Correct typo in French translation

apps/web/src/components/TeeFooterCookiesButton.vue, apps/web/src/components/consent/TeeDsfrConsent.vue, apps/web/src/components/consent/TeeDsfrPersonalizeConsent.vue, apps/web/src/utils/analytic/posthog.ts, apps/web/src/utils/cookies.ts
- on ne refresh plus la page quand on change les cookies
- avant de changer le type de persistence, on récupère l'id posthog pour le remettre et éviter la duplication
- on ne change pas le type de persistence si initialement on refuse les cookies (pas de changement de persistence comme posthog et initialisé avec memory) 
Tests effectués en local >> l'id ne change pas dans les event sur le dashboard de posthog
=> Fix : cookieless siret, plus de duplication des personnes

apps/web/src/components/program/detail/ProgramDetail.vue, apps/web/src/components/program/detail/ProgramEligibilityBar.vue
Sur  
https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise/diag-ecoconception?siret=83014132100034&effectif=TPE
Le premier CTA : [Voir les autres critères à respecter]; ne fait rien. 
Je pense que c'est la maj du dsfr qui est à l'origine de la regression. 
Je ne suis pas certain du comportement précédent d'où les reviews.
C'est plutôt prioritaire donc n'hésitez pas à faire els modifs vous même / à envoyer en prod si vous êtes le 2ème reviewer ! 
Note : j'ai mis un hash en francais car c'est visible par l'utilisateur lorsqu'il hover sur le bouton.
=> fix:  "see other criteria" button

apps/nuxt/src/server/api/__sitemap__/projects.ts
Remplacement de ProjectApi par ProjectService pour récupérer les projets. Isolation du backend par utilisation d'un service du ddd
=> hotfix: sitemap

apps/nuxt/src/server/api/programs/[programId].get.ts, libs/backend-ddd/src/program/domain/programFeatures.ts
- fix a EstablishementNotFound into ProgramNotFound
Je confirme que `createError` transmet l'erreur à sentry avec une 500 mais pas avec une 404. 
(J'ai testé en créant une 404 et en commentant le bloc qui change le comportement pour les 404. Il y a création d'un erreur avec le message d'erreur custom qui montre que c'est bien le create error qui créé l'erreur. 
Au contraire, en remettant le bloc spécifique 404, il n'y a plus de création d'erreur automatique. )
=> feat: improve backend program not found error monitoring

apps/nuxt/src/components/identification/details/TeeProfileDetails.vue, apps/nuxt/src/tools/companyData/companyData.ts, libs/backend-ddd/src/establishment/domain/establishmentFeatures.ts, libs/backend-ddd/src/establishment/domain/types.ts, libs/backend-ddd/src/establishment/infrastructure/api/sirene/sirene.ts
Les erreurs playwright sont en partie due à l'erreur suivante : 
- lorsque la recherche est effectuée via l'api siren et qu'il n'y a pas de nom, le filtrage n'est plus réalisé , exemple avec cet url : https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=oui&dechets=oui&gestion-eau=oui&energie=oui&audit=non&siret=78893947800020&effectif=EI
Fix proposé : 
- dénomination optionelle dans le back
- set valeurs par défaut pour affichage front s'il n'y a pas de dénomination. 
Amélioration possible: 
- Lorsque l'on va directement sur [l'url au dessus](https://tee-preprod-pr1554.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-comm …
=> hotfix: no program found with null denominations (also fixing playwright error notifications)

apps/nuxt/src/components/catalog/CatalogProjects.vue, apps/nuxt/src/components/project/list/OtherProject.vue, apps/nuxt/src/components/questionnaire/result/list/ResultProjectList.vue
Petite refacto pour ajouter le CTA + formulaire côté catalogue projet.
Test fonctionnel en local OK
app review: https://tee-preprod-pr1565.osc-fr1.scalingo.io/
close #1485
=> feat: Ajout du CTA + form autre projet sur le catalogue des projects

apps/nuxt/src/components/program/detail/ProgramDetail.vue, apps/nuxt/src/components/project/details/ProjectDescription.vue, apps/nuxt/src/components/project/details/ProjectDetail.vue, apps/nuxt/src/tools/analytic/useExternalLinkTracker.ts
Proposition de code pour tracker facilement les liens externes lorsque sur les pages program et projets. 
Le code proposé tracke trop de lien (il tracke tous les liens de la page lorsque le détail d'un programme ou d'un projet est affiché) mais sachant que certains liens sont générés à la volée via Markdown.toHtml, je ne vois pas trop d'autres solutions. 
Et c'est pas trop un problème d'emettre trop d'event posthog qu'on peut supprimer au moment où on fait les stats.  
close #1704
=> feat: send posthog event on external link clicked on program or project

apps/nuxt/src/middleware/resetQueries.ts
close #1816 
Proposition complémentaire pour ne garder les paramètres de query qu'une seule fois : 
```
const isFirstVisit = !localStorage.getItem('hasVisited')
if (isFirstVisit) {
localStorage.setItem('hasVisited', 'true')
Object.keys(currentQuery).forEach((key) => {
if (key.toLowerCase().startsWith('utm')) {
newQuery[key] = currentQuery[key] as string
}
})
}
```
Je ne sais pas trop ce que tu en penses.
=> fix: allow utm queries in routes where the resetQueries middleware is applied

apps/nuxt/src/server/api/establishments/[query].get.ts, libs/backend-ddd/src/establishment/infrastructure/api/recherche-entreprise/recherche-entreprise.ts
Dans de très rares cas, l'api recherche entreprise renvoie des résutlat qui n'ont pas de SIRET. 
Cela cause des crashs du point d'API. 
Je propose d'ignorer ces quelques réponses. 
Si, dans le cas très peu probable, toutes 3 réponses renvoyées par l'API sont sans SIRET, je prend soin de mettre le nombre de réponse à zéro pour qu'il n'y ai pas de données contradictoires sur le front. 
Tests des deux cas avec les textes suivant dans le champ de la modale : "thones beton" et "ehpad 261".
Renaming de l'erreur sentry du point d'api establishment
=> fix: establishment search rare error (missing SIRET)

apps/nuxt/nuxt.config.ts
Ceci est un rollback, car je voulais voir un peu si ça améliorer les performances. Mais je ne suis pas convaincu et de plus, ça ne permet pas d’utiliser le cache navigateur
@ttdm Si tu as un avis sur la question ?
=> fix: disable inline styles in nuxt configuration (to use cache browser)

libs/backend-ddd/src/opportunity/domain/opportunityFeatures.ts, libs/backend-ddd/src/opportunity/domain/types.ts, libs/backend-ddd/src/opportunity/infrastructure/api/brevo/brevoDeal.ts, libs/backend-ddd/src/opportunity/infrastructure/api/brevo/types.ts, libs/backend-ddd/src/opportunityHub/domain/opportunityHubFeatures.ts, libs/backend-ddd/src/opportunityHub/domain/spi.ts, libs/backend-ddd/src/opportunityHub/infrastructure/api/opportunityHubAbstract.ts, libs/backend-ddd/src/opportunityHub/infrastructure/api/placedesentreprises/placeDesEntreprises.ts, libs/backend-ddd/src/opportunityHub/infrastructure/api/placedesentreprises/types.ts, libs/backend-ddd/tests/opportunityHub/infrastructure/api/mock/placeDesEntreprises.ts, libs/data/tools/brevoExport/brevoExport.py
Récupère l'identifiant Conseiller Entreprise et le transmet à Brevo. 
Le fait de parler directement de _ceId_ dans le code peut être discutable mais ça me parait important de bien identifier l'id de chaque partenaire et de ne pas avoir de "partnerId" qui peut facilement être confondu. 
L'implém à été testé;. 
Voir le dernier deal sur la pipeline de test de brevo. Pour simplifier la vérification, l'idce a été rajotué en temps que dernière colonne dans le tableau brevo (à cacher à nouveau lors de la mise en prod)
close #1926
=> feat: store ce id in brevo

apps/nuxt/nuxt.config.ts
Cette pull request met à jour le fichier `nuxt.config.ts` pour améliorer la configuration de la section `<head>` de l’application Nuxt en ajoutant la prise en charge de différents liens favicon et du manifeste web app.
* [`apps/nuxt/nuxt.config.ts`](diffhunk://#diff-f461d740e09cfb2bc7ab32a29f66921fc84a62f1f75f0fb6e1189a77abae3a4fL26-R32) : Ajout de plusieurs éléments `<link>` à la configuration `head`, incluant la prise en charge des favicons SVG et ICO, d’une icône Apple touch et d’un fichier manifeste web app.
=> feat: add favicon and web app manifest links to nuxt configuration

libs/data/src/common/validators/linkValidator.ts, libs/data/src/program/yamlGenerator/coreGenerator.ts, libs/data/src/program/yamlGenerator/eligibilityGenerator.ts, libs/data/src/program/yamlGenerator/objectiveGenerator.ts
- Détection des urls mortes dans de nouveaux champs. Couverture de tous les champs réécrits en markdown, et de tous les champs étant spécialement dédiés aux liens. 
- Petite refacto pour proposer de loger directement dans le LinkValidator. 
- Petites amélioration de naming
- Petites amélioration sur les annotations de types
- Suppression des tests de validité effectués à tort dans les étapes sur les mails. 
Info tech: 
const myString : 'mailto:pda.hebergement@auvergnerhonealpes.fr'
const isEmail = z.string().email().safeParse(myString).success
const isUrl = z.string().url().safeParse(myString).success
console.log(match[2], isEmail, isUrl)
Renvoie :  false true
Cette string n'est donc pas un mail mais une url valide pour zod.
D'ou le check isEmail via : startwith(mailto) . 
La génération …
=> Feat: improve link checks in programs
