.env.example
README.md
src/TeeApp.ce.vue
src/components/TeeForm.vue
src/components/TeeMatomo.vue
src/components/TeeResults.vue
src/components/TeeTrack.vue
src/stores/analytics.ts
src/stores/programs.ts
src/utils/matomo.ts
vite.config.ts

Add Matomo setup and actions for analytics

Intégration des scripts matomo

---

.env.example
README.md
package.json
src/TeeApp.ce.vue
src/components/TeeForm.vue
src/components/TeeMatomo.vue
src/components/TeeResults.vue
src/components/TeeTrack.vue
src/stores/analytics.ts
src/stores/programs.ts
src/utils/matomo.ts
vite.config.ts

Merge staging into preprod
- add Matomo logic for tracking visits and events
- add a `VITE_NO_DEBUG_SWITCH` env variable

Staging to preprod

---

public/data/output/dataset_out.json
public/data/programs/visite-energie.yaml
src/components/TeeTrack.vue
src/components/TeeTrackInput.vue
src/questionnaire/trackSiret.ts
src/questionnaire/trackStructureSizes.ts
src/stores/programs.ts
src/types/index.ts
src/utils/conditions.ts
src/utils/helpers.ts
src/utils/requests.ts

Conditionnal next track depending on user choices and inputs

---

packages/web/index.html
packages/web/package.json
packages/web/public/css/custom.css
packages/web/src/TeeApp.ce.vue
packages/web/src/assets/custom.css
packages/web/src/components/TeeForm.vue
packages/web/src/components/TeeTrack.vue
packages/web/src/components/TeeTrackInput.vue
packages/web/src/utils/helpers.ts

Transitions in and out on tracks components

---

packages/backend/tests/api-sirene.test.ts
packages/web/src/questionnaire/trackSiret.ts

chore: change URL of the production backend

---

packages/web/public/css/custom.css
packages/web/src/TeeApp.ce.vue
packages/web/src/assets/custom.css
packages/web/src/components/TeeProgramDetail.vue
packages/web/src/components/TeeTrack.vue
packages/web/src/components/TeeTrackInput.vue
packages/web/src/questionnaire/trackBuildingProperty.ts
packages/web/src/questionnaire/trackEnergyReduction.ts
packages/web/src/questionnaire/trackMobility.ts
packages/web/src/questionnaire/trackNeeds.ts
packages/web/src/questionnaire/trackStrategyAudits.ts
packages/web/src/questionnaire/trackWastesStake.ts
packages/web/src/questionnaire/trackWaterStake.ts
packages/web/src/translations/fr.ts

UI & UX fixes

---

packages/web/public/css/custom.css
packages/web/src/assets/custom.css
packages/web/src/components/TeeProgramDetail.vue
packages/web/src/components/TeeTrackInput.vue
packages/web/src/questionnaire/trackEnergyReduction.ts
packages/web/src/questionnaire/trackMobility.ts
packages/web/src/questionnaire/trackWastesStake.ts
packages/web/src/questionnaire/trackWaterStake.ts

PR - UI fixes

---

packages/data/programs/diag-decarbon-action-eti.yaml
packages/data/programs/diag-decarbon-action-pme.yaml
packages/data/programs/diag-eco-flux-pme.yaml
packages/data/programs/diag-eco-flux-tpe.yaml
packages/data/programs/diag-ecoconception-eti.yaml
packages/data/programs/diag-ecoconception-pme.yaml
packages/data/programs/fonds-tourisme-durable.yaml
packages/data/programs/performa-environnement.yaml
packages/data/programs/tpe-gagnantes.yaml
packages/data/programs/visite-energie.yaml
packages/data/schemas/program-data-schema.json
packages/web/src/components/TeeProgramDetail.vue
packages/web/src/translations/fr.ts
packages/web/src/types/programTypes.ts

Adds data field "durée de l'accompagnement", conditionally required to `"nature de l'aide": "accompagnement"`.
- Update the JSON schema with a description
- Update the data accordingly
- Update the program page accordingly
screenshot : 
Solves #156

PR - data: add attribute "durée de l'accompagnement" 

---

packages/web/src/translations/fr-operators.ts

PR- fix: correct BPI label

---

packages/web/src/TeeApp.ce.vue
packages/web/src/components/TeeProgramDetail.vue
packages/web/src/components/TeeResults.vue
packages/web/src/components/TeeTrack.vue

PR - fix: add scrollToTop calls to TeeResults and TeeProgramDetail components

---

packages/web/public/css/custom.css
packages/web/src/assets/custom.css
packages/web/src/components/TeeTrackInput.vue
packages/web/src/questionnaire/trackSiret.ts

Fixes related to #199 
Result =>

PR - css and edito corrections on trackSiret + TeeTrackInput

---

package-lock.json
packages/web/package.json

Just remove quickly vuex from web's package dependency ! ;-)

fix: remove vuex dependency from web package

---

packages/web/src/components/TeeForm.vue
packages/web/src/components/TeeTrack.vue

- just a quick change to put icon arrow on the right on `DsfrButton` vue component with the prop `icon-right`
example:
```vue
<DsfrButton
:label="choices.t('send')"
:disabled="!canSaveFrom"
icon="ri-arrow-right-line"
icon-right
@click="saveFormData()"
/>
```

fix: change arrow position to right on tracks and contact pages

---

packages/web/src/questionnaire/trackResults.ts

fix: rename filter labels for objectifs prioritaires

---

packages/web/src/components/TeeAppFooter.vue

fix: update link label for accesibilite

---

packages/web/src/components/TeeAppFooter.vue

fix: update link label for accesibilite (#297)

---

packages/web/src/questionnaire/trackResults.ts

fix: resolution issue 303 - edito

---

packages/web/src/WebApp.vue

Add vue-dsfr CSS import in WebApp.vue

fix: css to display right arrow on button

---

packages/web/src/WidgetApp.ce.vue

fix: error with TrackId on WidgetApp file

---

packages/web/src/components/TeeHeader.vue
packages/web/src/types/routeType.ts

fix: responsive burger is now functional

---

packages/web/index.html

Changer le titre du site balise Title
"ADEME - Transition Ecologique des Entreprises - POC" par "Transition écologique des entreprises"

fix: change html head title

---

packages/web/src/translations/fr.ts

[Bug d'affichage sur l'avantage fiscal Flotte de vélos#305](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/305)

fix: add missing translation to display form title on fiscal advantage program type

---

README.md
packages/web/src/questionnaire/trackWastesMaterials.ts

fix: change main label of track wastes question

---

packages/web/src/pages/TeeProgramPage.vue
packages/web/src/router/index.ts

cf: #401
Le composant `WidgetApp` a été enlever de la page `TeeProgramPage`.
La route `questionnaire-detail` n'est pas utilisé, elle est donc supprimé

fix: remove widget component from TeeProgramPage and remove unused route

---

packages/web/src/pages/TeePersonalDataPage.vue

- fix #432 
- Suppression des textes au sujet de hotjar

feat: remove all text about hotjar

---

packages/data/programs/audit-energetique-en-industrie.yaml
packages/data/programs/booster-eco-energie-tertiaire.yaml
packages/data/programs/etude-economie-de-la-fonctionnalite.yaml
packages/data/programs/etude-et-investissement-qualite-de-l’air.yaml
packages/data/programs/etude-gaspillage-alimentaire.yaml
packages/data/programs/etude-hydroelectricite.yaml
packages/data/programs/etude-methanisation.yaml
packages/data/programs/etude-performance-energetique-en-industrie.yaml
packages/data/programs/etude-photovoltaique-2.yaml
packages/data/programs/etude-solaire-thermique.yaml
packages/data/programs/fonds-tourisme-durable.yaml
packages/data/programs/investissement-biognv-agricole-et-territorial.yaml
packages/data/programs/investissement-contre-le-gaspillage-alimentaire.yaml
packages/data/programs/investissement-methanisation.yaml
packages/data/programs/investissement-recuperation-de-chaleur-fatale.yaml
packages/data/programs/investissement-reemploi-reutilisation-reparation.yaml
packages/data/programs/investissement-solaire-thermique-metropole.yaml
packages/data/programs/investissement-solaire-thermique-outre-mer.yaml
packages/data/schemas/tools/XL2yaml/XL2yaml.py

Cf #266 et notamment [ce commentaire de Coline](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/266#issuecomment-1860690042) à ce sujet.

feat[data]: régions séparées par des virgules dans les conditions d'éligibilité

---

packages/web/public/robots.txt

- feat #439 
- Ajout du fichier robots.txt dans le dossier public
Ceci est une première version simple et sera revue en fonction des avancées sur les routes (routing partie questionnaire)
@JulienParis @pierrecamilleri 
note: peut être que pour améliorer le référencement, nous pourrions envisager de passer sous nuxt pour le SSR (?)
- partie serveur API: https://nuxt.com/docs/guide/directory-structure/server

feat(seo): first version of robots.txt

---

packages/web/src/router/index.ts
packages/web/src/router/redirection.ts

- feat #440 
- Simple renommage des url concernant la partie `/annuaire` pour des url du type `/aides-entreprise`
- redirection des anciennes url sur les nouvelles

feat(url): replace /annuaire* url to /aides-entreprise* and add redirect

---

packages/backend/src/domain/services/contact-service.ts
packages/backend/src/domain/services/establishment-service.ts

Use relative imports instead.
Fixes error introduced in #455

fix: error with @tee/backend imports.

---

packages/web/src/components/program/ProgramEligibility.vue

Améliore le typage de #441  (merci @yvalentin)

refactor: typage de "order"

---

packages/web/src/components/TeeForm.vue
packages/web/src/components/program/TeeProgramDetail.vue
packages/web/src/components/results/TeeResults.vue
packages/web/src/stores/analytics.ts

fix(matomo): add event name when event from catalog. And fix send event without value (undefined)

---

packages/web/src/components/TeeForm.vue
packages/web/src/components/program/TeeProgramDetail.vue
packages/web/src/components/results/TeeResults.vue
packages/web/src/stores/analytics.ts

preprod to prod

---

packages/data/programs/coup-de-pouce-chauffage.yaml

Ne pas proposer Coup de pouce chauffage aux secteurs :
- C Industrie manufacturière
- F Construction
fixes #391

feat(data): maj coup de pouce chauffage

---

SECURITY.md

docs: first draft for SECURITY.md

---

packages/web/public/css/custom.css
packages/web/src/assets/custom.css
packages/web/src/components/program/ProgramAccordion.vue
packages/web/src/components/program/ProgramEligibility.vue
packages/web/src/components/program/ProgramLongDescription.vue
packages/web/src/components/program/TeeProgramDetail.vue

accordion component w/ slot for both eligibility and long description in detail page

---

packages/web/src/WebApp.vue
packages/web/src/components/TeeFooter.vue

Des petites correction dans le component Footer
- suppression du props inutile `debug`
- suppression d'une chaine de caractère à la fin du fichier

fix: debug props and remove string at the end of file

---

packages/backend/src/operator/infrastructure/api/bpi/opportunityPayloadDTO.ts
packages/backend/src/opportunity/domain/types.ts

fix: add null possibility on company name to opportunity

---

packages/web/index.html

feat(seo): update title and description meta

---

packages/web/src/router/index.ts

Redirection des pages/urls non trouvées sur la homepage

fix(router): redirect page not found

---

packages/web/src/WebApp.vue
packages/web/src/WidgetApp.ce.vue
packages/web/src/components/program/detail/ProgramDetail.vue
packages/web/src/components/program/list/ProgramList.vue
packages/web/src/components/questionnaire/TeeQuestionnaire.vue
packages/web/src/pages/TeeQuestionnairePage.vue
packages/web/src/router/hook.ts
packages/web/src/stores/navigation.ts

change navigationStore to useNavigationStore

refactor Navigation store

---

packages/web/public/css/custom.css
packages/web/src/assets/custom.css
packages/web/src/components/TeeFooter.vue
packages/web/src/components/TeeTile.vue
packages/web/src/components/home/TeeHomeSteps.vue
packages/web/src/components/program/ProgramAccordion.vue
packages/web/src/components/program/ProgramObjective.vue
packages/web/src/components/program/TeeProgramDetail.vue

fixes for responsive

---

packages/web/public/css/custom.css
packages/web/src/WebApp.vue
packages/web/src/assets/main.css
packages/web/src/assets/main.scss
packages/web/src/assets/scss/accordion.scss
packages/web/src/assets/scss/card.scss
packages/web/src/components/program/ProgramAccordion.vue
packages/web/src/components/program/ProgramEligibility.vue
packages/web/src/components/program/ProgramLongDescription.vue
packages/web/src/components/program/TeeProgramDetail.vue
packages/web/widget/widget.ce.ts

affichage des conditions d'éligibilité et amélioration des transitions pour les accordéons avec le composant DsfrAccordion
Certain dispositif n'ont plus de conditions d'éligiblité d'affiché
[#640](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/640)

fix: affichage des conditions d'éligibilité

---

packages/data/programs/aides-au-reemploi-des-emballages.yaml
packages/data/programs/etude-biodechets.yaml
packages/data/programs/etude-reemploi-reutilisation-reparation.yaml
packages/data/programs/extreme-defi-mobilite.yaml
packages/data/programs/fond-vert-territoires-d-insdustrie.yaml
packages/data/programs/investissement-gestion-des-biodechets.yaml
packages/data/programs/investissement-reemploi-reutilisation-reparation.yaml
packages/data/programs/pret-action-climat.yaml
packages/data/programs/pret-economies-d-energie-pee.yaml
packages/data/programs/pret-vert-ademe.yaml
packages/data/programs/pret-vert.yaml
packages/data/tools/XL2yaml/README.md
packages/data/tools/XL2yaml/XL2yaml.py

Mise-à-jour des données. 
Première mise-à-jour des données après fusion des onglets Data et DataProd, donc petits rectificatifs nécessaire dans les données. Les erreurs provenaient du fait que les derniers dispositifs ajoutés (8 dispositifs ADEME) existaient dans les deux onglets et ont été édité en concurrence dans chacun des onglets. Je n'ai gardé que la version avec les modifications "éditoriales", mais j'ai dû refaire les modifications en lien avec la qualité des données (par exemple :  "Nouvelle-Aquitaine" au lieu de "Nouvelle Aquitaine"). 
Par ailleurs, le renommage du schema (dans la PR #639) m'a fait perdre des modifications du script apportées dans #603. Voilà qui est rétabli.

data: Mise à jour des données

---

packages/web/src/components/program/list/ProgramFilters.vue
packages/web/src/stores/program.ts

feat: remove objective filter on result page when specific goal track is done

---

packages/data/tools/brevoExport/README.md
packages/data/tools/brevoExport/brevoExport.py

Code fonctionnel mais horrible. 
Le résultat est visible dans notion => "tableurs / données" => Export Brevo
J'ai du reconstruire les objectifs à partir du questionnaireData disponible sur Brevo dans "autre_données". 
( Globalement j'ai recodé la logique interne dispo du fichier preprocessProgramsPublicodes )
C'est VRAIMENT pas terrible mais il n'y a pas d'autre solution pour l'instant.

feat: update brevo export with latest data format

---

packages/backend/src/opportunity/infrastructure/api/brevo/brevoDeal.ts
packages/backend/src/statistics/application/statisticsService.ts
packages/backend/src/statistics/domain/statisticsCache.ts
packages/backend/src/statistics/domain/statisticsFeatures.ts
packages/backend/tests/opportunity/createOpportunity.test.ts
packages/common/src/stats/types.ts
packages/web/src/components.d.ts
packages/web/src/components/element/TeeCallout.vue
packages/web/src/pages/TeeStatPage.vue
packages/web/src/types/elementsPropsTypes.ts

J'ai appliqué la grande majorité de tes suggestions. 
Pas grand chose à signaler mais en review par principe.

chore: cleaning the page stats update

---

packages/data/programs/communauté-coq-vert.yaml
packages/data/programs/etude-performance-produits.yaml
packages/data/programs/etude-photovoltaique-cci.yaml
packages/data/programs/mission-conseil-rse.yaml
packages/data/programs/renovation-energetique.yaml
packages/data/programs/tremplin.yaml
packages/data/tools/XL2yaml/XL2yaml.py

Ajout de deux programmes. 
Petites modif sur 4 programmes déjà en prod. 
Petite maj du script python pour suivre l'évolution du fichier partagé.

chore: update program data

---

packages/web/src/components/program/list/filters/ProgramFiltersAccordion.vue
packages/web/src/utils/track/trackStructure.ts

- fix also getEligibityCriteria to avoid undefined value

fix: remove operator filter on result page from track

---

packages/common/src/questionnaire/types/questionnaireData.ts

fix: add legalCategory on QuestionnaireData to allow it on programController queries validation

---

packages/web/src/translations/fr/program.ts

Demandé par PDE, validé par JB, modif mineure
close #773 
Review par principe, je merge à la première validation.

minor: change form description

---

packages/data/programs/pret-vert-ademe.yaml

Modifie la date de fin du prêt vert de l'ademe qui n'est plus disponible.

chore: update program end of life

---

packages/common/src/establishment/validator/siretValidator.ts

fix #823
Je vous met tous les trois en reviewer : le/la premier⋅e qui a le temps de faire la review...

fix: add undefined check in siretValidator

---

packages/web/src/assets/scss/input.scss

style: update input style.scss to hide default valid field icon

---

apps/web/src/components/program/detail/ProgramForm.vue

Fix: update textarea and callout styles in ProgramForm

---

apps/web/src/components/home/TeeCta.vue

Nouveau texte : "Je complète mon profil en moins de 2 minutes, et j’accède à propositions d’actions et de financements pour m'aider à réduire mon impact environnemental."

fix: changement du texte de la page d'accueil

---

libs/data/programs/adaptation-bzh.yaml
libs/data/programs/bonus-reparation.yaml
libs/data/programs/ecoconception-bzh.yaml
libs/data/programs/ecogestes-paca.yaml
libs/data/programs/tourisme-durable-paca.yaml
libs/data/src/program/publicodesGenerator.ts

feat: add new programs

---

apps/web/src/utils/theme.ts

le tag HR est ajouté dans les tags de thématique pour les 2 parcours
close #913

feat: add HR objective to theme tags by default

---

apps/web/src/components/program/detail/ProgramForm.vue
apps/web/src/components/project/details/ProjectForm.vue
apps/web/src/router/routes.ts
apps/web/src/service/api/opportunityApi.ts
apps/web/tsconfig.json
libs/backend-ddd/src/opportunity/domain/types.ts
libs/backend-ddd/src/opportunityHub/infrastructure/api/placedesentreprises/placeDesEntreprises.ts
libs/backend-ddd/tests/opportunity/testing.ts
libs/common/src/opportunity/opportunityTypes.ts

Remplacement des liens envoyés à PDE par les liens vers les catalogues
close #911

feat: improve the link sent to PDE

---

apps/web/src/components/project/details/ProjectHeader.vue

- correction de l'appel à la function qui permet de vérifier si la route actuelle est le détail d'un projet côté catalogue

Fix: method call used as constraint on TeeEligibilityCriteriaBar display in ProjectHeader

---

apps/web/src/components.d.ts
apps/web/src/components/project/details/ProjectPrograms.vue
apps/web/src/components/project/details/ProjectProgramsList.vue
apps/web/src/translations/fr/project.ts

- ajout d'un composant ProjectProgramsList avec un titre + styling du titre

Feature : distinguer les types d'aides pour les listes d'aides dans le détail d'un projet

---

libs/backend-ddd/src/opportunityHub/infrastructure/api/placedesentreprises/placeDesEntreprises.ts

feat: improve project mapping when transmitting projects to PDE

---

.github/workflows/tests.yml
.github/workflows/update_data.yml

tentative de fix pour les erreurs sur la CI de github en relation avec `nx` (voir: https://github.com/nrwl/nx/issues/26517)

fix(ci): add option "--foreground-scripts" on npm clean-install

---

apps/web/src/components/program/detail/ProgramForm.vue
apps/web/src/components/project/details/ProjectForm.vue

- Ajout d'une computed property `isFormValid` pour le `ProgramForm.vue` et le `ProjectForm.vue` pour vérifier la vadlidité de l'ensemble des champs du formulaire avant soumission. 
- Cette validation déclencher l'activation du bouton de soumission du formulaire.

fix: Ensure form validity before enabling submit buttons

---

apps/web/src/components/track/TrackSidebar.vue
apps/web/src/questionnaire/trackBuildingProperty.ts
apps/web/src/questionnaire/trackEnergyReduction.ts
apps/web/src/questionnaire/trackGoals.ts
apps/web/src/questionnaire/trackMobilityWishes.ts
apps/web/src/questionnaire/trackQuestionnaireRoute.ts
apps/web/src/questionnaire/trackStrategyAudits.ts
apps/web/src/questionnaire/trackStrategyAuditsSelect.ts
apps/web/src/questionnaire/trackStructureRegion.ts
apps/web/src/questionnaire/trackStructureSectors.ts
apps/web/src/questionnaire/trackStructureSiret.ts
apps/web/src/questionnaire/trackStructureWorkforce.ts
apps/web/src/questionnaire/trackWastesMaterials.ts
apps/web/src/questionnaire/trackWastesSorting.ts
apps/web/src/questionnaire/trackWastesStake.ts
apps/web/src/questionnaire/trackWaterStake.ts
apps/web/src/translations/fr.ts
apps/web/src/types/track/trackType.ts

feat: add "myProject" category on goal track

---

libs/data/programs/cedre-investissement.yaml
libs/data/programs/cedre-premier-pas.yaml
libs/data/programs/cheque-transition-bioethanol.yaml
libs/data/programs/diag-decarbon-action.yaml
libs/data/programs/investour.yaml
libs/data/programs/nature-ta-ville.yaml
libs/data/programs/navires-energies-propre.yaml
libs/data/programs/recharge-vehicule-electrique.yaml
libs/data/programs/sites-touristiques-exemplaires.yaml
libs/data/programs/smart-pv.yaml
libs/data/programs/solaire-ready.yaml
libs/data/programs/sud-pret-climat.yaml
libs/data/schemas/program-with-publicodes-schema.json

chore: updata data and rename one operator

---

apps/web/src/components/home/TeeHomeInfos.vue

- Plus de notion de préremplissage de theme dans les CTA qui entrainaient des erreurs en cascade (vu avec Coline comme de toute façon les CTA vont disparaitre)

Fix : Bug sur les résultats au clic sur l'un des 4 CTA "je me lance" de la page d'accueil

---

.github/workflows/update_data.yml
libs/data/src/common/validators/linkValidator.ts
package-lock.json
package.json

Playwright chrome ne veut pas start

fix: data daily cron

---

apps/web/src/components/catalog/CatalogPrograms.vue
apps/web/src/components/catalog/CatalogProjects.vue
apps/web/src/components/element/form/TeeForm.vue
apps/web/src/components/program/detail/ProgramDetail.vue
apps/web/src/components/questionnaire/result/list/ResultList.vue
apps/web/src/components/questionnaire/result/list/ResultListInTabs.vue
apps/web/src/components/track/TrackContent.vue
apps/web/src/components/track/form/TrackSiret.vue
apps/web/src/utils/analytic/analytics.ts

Suppression des evenements inutiles (on garde uniquement les formulaires) cf (https://github.com/betagouv/mission-transition-ecologique/issues/747)
Changement de l'ordre des arguments dans analytics

Hot fix : Posthog

---

apps/web/src/service/api/opportunityApi.ts

Plus d'utilisation de useRouter à l'extérieur d'un composant >> fix refactorisation des formulaires

Hot fix : Formulaire

---

apps/backend/src/controller/program/programsController.ts

chore: change sentry error level

---

apps/web/src/router/index.ts
apps/web/src/utils/analytic/posthog.ts
package-lock.json
package.json

- ajout d'une fonction capturePageLeave dans utils/analytics/posthog
- mise à jour de posthog

Fix : mise à jour de posthog + page leave event

---

apps/web/src/components/program/detail/ProgramDetail.vue
apps/web/src/utils/scroll.ts

Proposition de double fix : 
- Ajoute le cas spécifique CatalogProgramFromCatalogProjectDetail dans scroll to program form
- Dans Scroll.toWithTopBarOffset, scroll.to l'élément s'il n'existe pas de topbaroffset plutôt que de ne rien faire. 
Comportement actuel : 
https://mission-transition-ecologique.beta.gouv.fr/projets-entreprise/sensibilisation-equipes/investour
Fix : 
(quand scalingo sera up)

fix: cta conseiller 

---

apps/web/src/components.d.ts
apps/web/src/components/identification/TeeRegisterHighlight.vue
apps/web/src/components/project/details/ProjectPrograms.vue
apps/web/src/translations/fr/project.ts

Ajout d'un composant TeeRegisterHighlight
Changement condition de l'affichage du composant avec v-if="!CompanyDataStorage.hasData()"
To do : brancher avec la modale (inject/provide déjà en place dans la branche siret-modale)
#1132

Feature : Je complète mon profile sur la fiche projet

---

README.md
package.json

Dites moi si vous voulez changer quelques choses

docs: add contributors core team

---

apps/backend/src/controller/establishment/establishmentController.ts
apps/web/src/components/identification/TeeRegisterModal.vue
libs/backend-ddd/src/establishment/domain/establishmentFeatures.ts
libs/backend-ddd/src/establishment/domain/types.ts
libs/backend-ddd/src/establishment/infrastructure/api/recherche-entreprise/recherche-entreprise.ts
libs/backend-ddd/src/establishment/infrastructure/api/recherche-entreprise/type.ts
libs/backend-ddd/src/establishment/infrastructure/api/sirene/sirene.ts
libs/backend-ddd/src/establishment/infrastructure/api/sirene/types.ts
libs/backend-ddd/tests/establishment/testing.ts

On avait déjà tout de prêt.
PR assez basique.
@oumeimaelisbihani je te tag seule sur la review pour te remercier pour avoir déjà tout préparer proprement avec l'EI donc je n'avais quasi rien à faire sur le front ! Merci :)
close #1204

feat: auto fill the structure size

---

apps/backend/src/controller/establishment/establishmentController.ts
apps/web/src/components/identification/TeeRegisterModal.vue
libs/backend-ddd/src/establishment/domain/establishmentFeatures.ts
libs/backend-ddd/src/establishment/domain/types.ts
libs/backend-ddd/src/establishment/infrastructure/api/recherche-entreprise/recherche-entreprise.ts
libs/backend-ddd/src/establishment/infrastructure/api/recherche-entreprise/type.ts
libs/backend-ddd/src/establishment/infrastructure/api/sirene/sirene.ts
libs/backend-ddd/src/establishment/infrastructure/api/sirene/types.ts
libs/backend-ddd/tests/establishment/testing.ts

Feature: ajoute automatiquement une proposition de taille d'entreprise lors de la sélection d'un siret
On avait déjà tout de prêt.
PR assez basique.
close #1204

feat: auto-fill structure size

---

apps/web/src/components/header/TeeDsfrHeader.vue

Eliminated input fields and methods related to company data storage from TeeDsfrHeader.vue since they were no longer needed. This cleanup simplifies the component and removes redundant dependencies and functionalities.

refactor: Remove unused company data storage features

---

apps/web/src/components/catalog/CatalogPrograms.vue
apps/web/src/components/catalog/CatalogProjects.vue
apps/web/src/components/element/TeeNoResult.vue
apps/web/src/components/identification/TeeRegisterCTA.vue
apps/web/src/components/program/detail/ProgramDetail.vue
apps/web/src/components/program/detail/ProgramEligibilityBar.vue
apps/web/src/components/project/list/ProjectList.vue
apps/web/src/components/questionnaire/result/list/ResultProgramList.vue
apps/web/src/components/questionnaire/result/list/ResultProjectList.vue
apps/web/src/utils/opportunity.ts
apps/web/src/utils/storage/companyDataStorage.ts

This pull request includes multiple changes across various components to improve the user interface and functionality. The most important changes include adjustments to the spinner display, enhancements to the `TeeNoResult` component, updates to the `TeeRegisterCTA` component, and modifications to the `ResultProgramList` and `ResultProjectList` components.
* [`apps/web/src/components/catalog/CatalogPrograms.vue`](diffhunk://#diff-f4ac6ff7f753cfd3db0f405f4c5c9c0960f9b745b215504b2d6df618d51b0ac5L39-R42): Adjusted the `TeeSpinner` component to include a new class for margin-top.
* [`apps/web/src/components/catalog/CatalogProjects.vue`](diffhunk://#diff-daa3a95ecbc081f321de5f2f4d3a09980349763690530e01665ddfb6c9387e3aL43-R45): Added a new class to the `TeeSpinner` component for margin-top and …

fix: Update UI components for spinner logic and add functionality from review

---

apps/web/src/components.d.ts
apps/web/src/components/TeeFooter.vue
apps/web/src/pages/TeeBudgetPage.vue
apps/web/src/router/routes.ts
apps/web/src/types/routeType.ts

Feat: page budget

---

apps/web/src/components/questionnaire/result/list/ResultProgramList.vue
apps/web/src/components/questionnaire/result/list/ResultProjectList.vue

Utilisation du spinner du navigation store #1357

Hotfix: corriger le comportement du filtre sur la page de résultat d'aides sur le parcours je ne sais pas par où commencer

---

apps/web-e2e/src/formResults.spec.ts
apps/web-e2e/src/formResultsData.ts

Fix : track manual recording playwright

---

apps/web/src/components/project/details/ProjectPrograms.vue
apps/web/src/translations/fr/project.ts

Remonter l'encart "Je complète mon profil" sur un projet

---

libs/backend-ddd/src/opportunity/domain/opportunityFeatures.ts

PR pour fix : 
https://sentry.incubateur.net/organizations/betagouv/issues/135164/?environment=prod&project=138&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

fix: backend error in create opportunity

---

libs/data/programs/etude-geothermie-de-surface-et-d-aerothermie.yaml

Fix une erreur ajoutée lors d'une mise à jour des données.

fix: program data correction

---

apps/nuxt/src/components/home/TeeHomeInfos.vue

close #1034 et vu avec @celinebagault

Minor fix : Fix typo home page "éléctricité" au lieu "électricité" et changement du texte associé

---

apps/nuxt/.env.dist
apps/nuxt/README.md
apps/nuxt/src/config.ts
apps/nuxt/src/env.d.ts

Nettoyer des variables d'environnement sur Scalingo et donc dans le code aussi.
- Suppression des var inutile
- Petite mise à jours du .env.dist et du readme

chore: clean .env

---

apps/nuxt/src/components/project/details/ProjectDetail.vue
apps/nuxt/src/pages/projets-entreprise/[projectSlug]/index.vue

utilisation de la couleur du projet

Fix: couleur de la thématique dans les exemples de projet depuis une aide

---

apps/nuxt/src/components/element/form/TeeForm.vue
apps/nuxt/src/components/project/details/ProjectPrograms.vue
apps/nuxt/src/components/project/list/OtherProjectForm.vue
apps/nuxt/src/translations/fr/project.ts

close #1491 pas de review comme juste un changement de text

Modifier l'accroche du formulaire de contact sur les fiches projet

---

libs/backend-ddd/src/opportunity/domain/opportunityFeatures.ts
libs/backend-ddd/src/opportunityHub/domain/opportunityHubFeatures.ts

feat: dont send receipt mail when opportunites are transmitted to CE

---

apps/nuxt/src/components/filters/FilterByCompanyData.vue
apps/nuxt/src/components/filters/FiltersAccordion.vue
apps/nuxt/src/components/identification/TeeRegisterModal.vue
apps/nuxt/src/components/program/list/filters/ProgramFiltersAccordion.vue
apps/nuxt/src/stores/filters.ts
apps/nuxt/src/stores/program.ts
apps/nuxt/src/stores/project.ts
apps/nuxt/src/tools/program/programFilter.ts
apps/nuxt/src/tools/project/projectFilter.ts
apps/nuxt/src/types/filters/filtersTypes.ts

- fix de la réactivité du filtre région
- refacto de la partie `companyData` dans le `filterStore` (extraction du filtre pour le rendre autonome)
close #1597

hotfix: Refactor company data filter handling in filters store

---

apps/nuxt/src/components/program/detail/ProgramDetail.vue
apps/nuxt/src/tools/program/programManager.ts

- Gestion du programme detail sur un refresh de page (en mode connecté)

hotfix: update program detail component

---

apps/nuxt/src/components/questionnaire/track/form/TrackSiret.vue

Fix : TypeError: Cannot read properties of undefined (reading 'siret') 

---

apps/nuxt/src/components/contact/ContactMail.vue
apps/nuxt/src/pages/TeeAddProgram.vue

close #1535 https://tee-preprod-pr1680.osc-fr1.scalingo.io/ pour tester

Improvement : Mise en avant de l'adresse générique contact@ à destination des opérateurs publics/fédérations qui arrivent sur le site 

---

apps/nuxt/src/components/project/details/LinkedProjects.vue
apps/nuxt/src/components/project/details/ProjectSideNav.vue
apps/nuxt/src/translations/fr/project.ts

Pareil une seule review comme c'est du minor fix : https://tee-preprod-pr1663.osc-fr1.scalingo.io/projets-entreprise/plan-action-eau 
close #1447

Refacto : transformer les projets complémentaires en "pré-requis"

---

apps/nuxt/src/components/home/TeePromises.vue

pas de review tech comme c'est que du texte. close #1689

Fix : Modifier le wording de la page d'accueil 

---

apps/nuxt/src/components/TeeFooter.vue

feat: enhance footer with ADEME logo and mission description

---

apps/nuxt-e2e/src/form/formResults.spec.ts
apps/nuxt/src/components/element/form/TeeFormElementCheckbox.vue
apps/nuxt/src/pages/TeePersonalDataPage.vue
apps/nuxt/src/tools/opportunity.ts
apps/nuxt/src/types/opportunityFormType.ts

Minor change : Mettre à jour la page Données perso et opt-in du formulaire

---

apps/nuxt/src/tools/companyData/companyData.ts

app review https://tee-preprod-pr1753.osc-fr1.scalingo.io/
closes #1563

fix: simplify denomination assignment in company data handling

---

apps/nuxt/src/components/TeeFooter.vue
apps/nuxt/src/components/TeeHeader.vue
apps/nuxt/src/components/TeeIframe.vue
apps/nuxt/src/components/element/TeeBanner.vue
apps/nuxt/src/components/home/TeeCta.vue
apps/nuxt/src/components/home/TeePromises.vue
apps/nuxt/src/components/program/detail/ProgramImage.vue
apps/nuxt/src/components/program/list/ProgramCard.vue
apps/nuxt/src/components/project/list/ProjectCard.vue
apps/nuxt/src/components/theme/ThemeHeaderCard.vue
apps/nuxt/src/tools/image.ts
apps/nuxt/src/tools/opportunity.ts

- implement new class Image
- replace NuxtImg with img from Image class to handle across multiple components and better management to use or not external tool like Nuxt Image
Seems to have too many crash of prod server

fix: rollback image optimisation

---

apps/nuxt/src/assets/main.scss
apps/nuxt/src/assets/scss/markdown.scss
apps/nuxt/src/components/program/detail/ProgramEligibilityConditions.vue
apps/nuxt/src/components/program/detail/ProgramObjective.vue
apps/nuxt/src/tools/marked.ts

Modif effectuée suite à une demande de Coline.
A titre de comparaison : 
Avant : https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise/accelerateur-decarbonation
Après : https://tee-preprod-pr1900.osc-fr1.scalingo.io/aides-entreprise/accelerateur-decarbonation
close #1901

feat: always delete the line spacing in markdown imported content

---

apps/nuxt/src/components/TeeIframe.vue

Gestion des media queries pour éviter que le logo déborde sur le bas

fix: enhance iframe image responsiveness with media queries

---

apps/nuxt/src/components/program/detail/ProgramDetail.vue
apps/nuxt/src/components/project/details/ProjectDetail.vue
apps/nuxt/src/pages/TeeAccessibilityPage.vue
apps/nuxt/src/pages/TeeAddProgram.vue
apps/nuxt/src/pages/TeeBudgetPage.vue
apps/nuxt/src/pages/TeeHomePage.vue
apps/nuxt/src/pages/TeeLegalPage.vue
apps/nuxt/src/pages/TeePersonalDataPage.vue
apps/nuxt/src/pages/TeeStatPage.vue
apps/nuxt/src/pages/aides-entreprise/index.vue
apps/nuxt/src/pages/projets-entreprise/index.vue

Ajout des canonicales sur les pages (sauf questionnaire et iframe)

feat: add canonical links to various pages for improved SEO

---

apps/nuxt/src/tools/analytic/posthog.ts

feat: posthog config improvement

---

apps/nuxt/src/pages/TeeBudgetPage.vue

feat: update budget page

---

apps/nuxt/src/components/program/detail/ProgramForm.vue
libs/backend-ddd/src/opportunityHub/infrastructure/api/placedesentreprises/placeDesEntreprises.ts

lié à https://github.com/betagouv/mission-transition-ecologique/issues/2117

feat: transmit autonomous program opportunities to CE
